/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_dexshell_DexLoadJni */

#ifndef _Included_com_android_dexshell_DexLoadJni
#define _Included_com_android_dexshell_DexLoadJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_dexshell_DexLoadJni
 * Method:    changeClassLoader
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_com_android_dexshell_DexLoadJni_changeClassLoader
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_android_dexshell_DexLoadJni
 * Method:    changeApplication
 * Signature: (Landroid/content/Context;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_android_dexshell_DexLoadJni_changeApplication
  (JNIEnv *, jclass, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
